libxgboost=2.1.1 xgboost=2.1.1 py-xgboost=2.1.1 scikit-learn=1.3.2 confidenceinterval=1.0.4 scipy=1.11.2 matplotlib=3.7.2 seaborn=0.12.2 numpy=1.25.2 numpy-base=1.25.2 pandas=2.0.3 pandas-flavor=0.6.0 _py-xgboost-mutex=2.0 
